export const courses = [
    {
        "id": "0001",
        "title": "Web dev basics",
        "content": "Life finds a way. God creates dinosaurs. God destroys dinosaurs. Life finds a way. God creates dinosaurs. God destroys dinosaurs. Life finds a way. God creates dinosaurs. God destroys dinosaurs. ",
        "pro": false,
        "challenges":[
            {
                "id": "1",
                challenge: "The following function doesn't return anything, please make tweak the javascript code to make it work.",
                html: "<h1>Hello </h1>",
                css:"h1 {\n  color: grey;\n}",
                javascript: `function returnGreet() {\n  const title = document.getElementsByTagName("h1")[0];\n  title.textContent += name;\n};\nreturnGreet("Carl");`,
            },
            // {
            //     "id": "2",
            //     challenge: "Please print 'Hello World!' to the console (mind the eclamation mark)!",
            //     html: "",
            //     css:"",
            //     javascript:"",
            // },
        ],
    },
    {
        "id": "0002",
        "title": "CSS basics",
        "content": "Must go faster... go, go, go, go, go! We gotta burn the rain forest, dump toxic waste, pollute the air, and rip up the OZONE! 'Cause maybe if we screw up this planet enough, they won't want it anymore! Yes, Yes, without the oops! Yeah, but John, if The Pirates of the Caribbean breaks down, the pirates don’t eat the tourists.",
        "pro": true,
        "challenges": [],
    },
    {
        "id": "0003",
        "title": "Javascript basics",
        "content": "I gave it a cold? I gave it a virus. A computer virus. God help us, we're in the hands of engineers. They're using our own satellites against us. And the clock is ticking. Forget the fat lady! You're obsessed with the fat lady! Drive us out of here! Yes, Yes, without the oops!",
        "pro": true,
        "challenges": [],
    },
    {
        "id": "0004",
        "title": "Web dev basics",
        "content": "Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus.",
        "pro": true,
        "challenges": [],
    },
    {
        "id": "0005",
        "title": "CSS basics",
        "content": "Must go faster... go, go, go, go, go! We gotta burn the rain forest, dump toxic waste, pollute the air, and rip up the OZONE! 'Cause maybe if we screw up this planet enough, they won't want it anymore! Yes, Yes, without the oops! Yeah, but John, if The Pirates of the Caribbean breaks down, the pirates don’t eat the tourists.",
        "pro": true,
        "challenges": [],
    },
    {
        "id": "0006",
        "title": "Javascript basics",
        "content": "I gave it a cold? I gave it a virus. A computer virus. God help us, we're in the hands of engineers. They're using our own satellites against us. And the clock is ticking. Forget the fat lady! You're obsessed with the fat lady! Drive us out of here! Yes, Yes, without the oops!",
        "pro": true,
        "challenges": [],
    },
    {
        "id": "0007",
        "title": "Web dev basics",
        "content": "Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus.",
        "pro": true,
        "challenges": [],
    },
    {
        "id": "0008",
        "title": "CSS basics",
        "content": "Must go faster... go, go, go, go, go! We gotta burn the rain forest, dump toxic waste, pollute the air, and rip up the OZONE! 'Cause maybe if we screw up this planet enough, they won't want it anymore! Yes, Yes, without the oops! Yeah, but John, if The Pirates of the Caribbean breaks down, the pirates don’t eat the tourists.",
        "pro": true,
        "challenges": [],
    },
    {
        "id": "0009",
        "title": "Javascript basics",
        "content": "I gave it a cold? I gave it a virus. A computer virus. God help us, we're in the hands of engineers. They're using our own satellites against us. And the clock is ticking. Forget the fat lady! You're obsessed with the fat lady! Drive us out of here! Yes, Yes, without the oops!",
        "pro": true,
        "challenges": [],
    },
    {
        "id": "0010",
        "title": "Web dev basics",
        "content": "Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus. Life finds a way. God creates dinosaurs. God destroys dinosaurs. God creates Man. Man destroys God. Man creates Dinosaurs. Hey, take a look at the earthlings. Goodbye! I was part of something special. I gave it a cold? I gave it a virus. A computer virus.",
        "pro": true,
        "challenges": [],
    },
    {
        "id": "0011",
        "title": "CSS basics",
        "content": "Must go faster... go, go, go, go, go! We gotta burn the rain forest, dump toxic waste, pollute the air, and rip up the OZONE! 'Cause maybe if we screw up this planet enough, they won't want it anymore! Yes, Yes, without the oops! Yeah, but John, if The Pirates of the Caribbean breaks down, the pirates don’t eat the tourists.",
        "pro": true,
        "challenges": [],
    },
]
